### ISSUE TITLE
Wrong link in README.md

### ISSUE THREAD

**Issue by breti** [eoncire/HA_bed_presence#2]
Hi,

thank you so much for sharing your project with us. I presented it at our local Smart Home get-together, one participant ordered the parts directly and will try it out (with FHEM).

We noticed a small issue in the documentation: In the README.md you have added the same YouTube link to both "Setup / Testing Video" and "Demo Video". Is there another video?

Thanks and best regards,
Breti

**Comment by eoncire** [comment]
Thanks for the heads up.  I just updated the README with the correct link.  Let me know if you have any other questions, thanks for checking out my project!

**Comment by breti** [comment]
Thanks a lot! 👍
