### ISSUE TITLE
Overview explanation

### ISSUE THREAD

**Issue by nappyjim** [eoncire/HA_bed_presence#6]
Im new to ESP of any kind.  This will be my first project. I am just trying to wrap my head around the overall schematic.

So you are connecting the 3v pin on the ESP32 board to terminal 1 on the breadboard, which then is jumped to 3 as well.

Your little screw on terminals add-ons where you attach the red wires from the pressure sensor film are connecting to terminals 1 and 3.

Terminal 5 (I think, hard to tell in picture) is where your connecting the black wires from the pressure sensor films, which is then connected to the GND pin of the ESP32.

So what I am confused about is how are the pressure sensor films reporting back voltage to the ESP32?  On the same red wires that your supplying the 3v on?

Thanks.

**Comment by eoncire** [comment]
I need to get some better schematics and photos....sorry.  Here is a better schematic.  You may need to try some different resistor values to see what works.  Different values gave different results / sensitivity of the film sensor.

![image](https://user-images.githubusercontent.com/45377685/118119720-d09b6300-b3bc-11eb-9555-3ed09411203b.png)

**Comment by nappyjim** [comment]
> I need to get some better schematics and photos....sorry. Here is a better schematic. You may need to try some different resistor values to see what works. Different values gave different results / sensitivity of the film sensor.
> 

Thanks, that helps me a lil more.

 So I tested it out, it does work, but with my wife on her side, the voltage only changes from 3.9v to 3.3v.  You said different resistors will change this.  Should I go with a lower resistor or high resistor if I want more "sensitivity"?

**Comment by tomlut** [comment]
Measure only the FSR resistance (no other connection) when loaded with your weight (Rl) and unloaded (Ru). For the maximum change use this resistor value:
```
R = sqrt(Rl * Ru)
```
