### ISSUE TITLE
Pressure starting with 3.9V instead of 0V

### ISSUE THREAD

**Issue by erd82** [eoncire/HA_bed_presence#7]
Hi, I have used a [ESP32 NodeMCU Module WiFi Dev Kit C Development Board with CP2102](https://www.amazon.de/gp/product/B074RGW2VQ/ref=ppx_yo_dt_b_search_asin_image?ie=UTF8&th=1) .
![image](https://user-images.githubusercontent.com/63564291/141457310-055fb12f-d2ca-4492-a3cb-b3869ab15517.png)

I am getting always 
inverted values beginning with 3.9V or below. It does not start from 0V increasing at pressure.
![bed-presence](https://user-images.githubusercontent.com/63564291/141457993-e4aa7024-4e21-4534-95df-cf6379b6e15b.gif)

What am I doing wrong or is the the reason? How invert this at the easiest?

**Comment by erd82** [comment]
In the meantime I could already answer the question myself :-). I needed to switch between GND and 3V3. Perfectly works now.

**Comment by aviv943** [comment]
> In the meantime I could already answer the question myself :-). I needed to switch between GND and 3V3. Perfectly works now.

I had the same problem. Thank you for your response, your solution of switching between GND and 3V3 worked perfectly and solved my problem too.
